### ISSUE TITLE
Fixes for libreoffice recipes

### ISSUE THREAD

**Issue by bkauler** [schnitzeltony/meta-office#4]
Building for MACHINE 'genericx86-64', target 'core-image-sato-sdk', with libreoffice added into bblayers.conf and local.conf. Cloned everything about a week ago, with "--depth 1", did not checkout a release version.

Unfortunately, I don't have the logs any more for these failures. Deleted that build. Now building with the .bb files modified as described below. However, will describe why I made the changes, and you might consider whether they should be accepted.

**clucene**
meta-office/recipes-libreoffice/libreoffice/libreoffice-native.bb has 'clucene' as a system dependency. However, clucene failed to build, so I changed to the internal clucene.
As far as I can see, this is a package not needed elsewhere (refer: http://clucene.sourceforge.net/), so no big deal in making it internal.

So, I have removed this line from libreoffice-native.bb:

`   --with-system-clucene \
`
And removed this line from libreoffice.bb:

`    clucene-core \
`
**unzip, neon**
Unpack of libreoffice-native reported that 'unzip' is missing, it also reported something about package 'neon' not being in the repository. Note: I do have unzip in my host system.

So I added these two dependencies to libreoffice-native.bb:

```
    unzip-native \
    neon-native \

```
and added this configure option:

`    --with-system-neon \
`
Note, libreoffice.bb already has "--with-system-neon".

In libreoffice.bb, I added unzip as a dependency:

`    unzip \
`
Although I can't provide logs of why these errors occurred, thought I would post these fixes here, for consideration, as they have enabled me to continue with the build of libreoffice. There are a couple of build errors -- I already posted about 'glm' do_install failing, and there is one more error with compiling the icons, will post about that soon. 
I applied workarounds for those two, and the build completes.

**Comment by schnitzeltony** [comment]
Sorry for long delay.

First update: For unzip- and neon-native case I followed your suggestion. The cluence-issue I cannot reproduce (yet).
