### ISSUE TITLE
icon-themes compile fail

### ISSUE THREAD

**Issue by bkauler** [schnitzeltony/meta-office#5]
I have reported on changes required for libreoffice.bb and libreoffice-native.bb:
https://github.com/schnitzeltony/meta-office/issues/4

With those fixes, libreoffice is off and running, compiling. Just hits two errors.

Package 'glm' has an install problem, reported here:
https://github.com/schnitzeltony/meta-office/issues/3

The second error is that the 'icon-themes' compile fails. Here is an extract from the log:

```
| [build MOD] oovbaapi
| S=/mnt/sda1/projects/oe/oe-project/buildQ/tmp/work/core2-64-poky-linux/libreoffice/5.0.6.3-r0/libreoffice-5.0.6.3 && I=$S/instdir && W=$S/workdir &&  mkdir -p $W/Module/ && touch $W/Module/oovbaapi
| [build PRL] CustomTarget/postprocess/images/images_\breeze\galaxy\hicontrast\oxygen\sifr\tango.zip
| S=/mnt/sda1/projects/oe/oe-project/buildQ/tmp/work/core2-64-poky-linux/libreoffice/5.0.6.3-r0/libreoffice-5.0.6.3 && I=$S/instdir && W=$S/workdir &&  /mnt/sda1/projects/oe/oe-project/buildQ/tmp/work/core2-64-poky-linux/libreoffice/5.0.6.3-r0/recipe-sysroot-native/usr/bin/perl-native/perl $S/solenv/bin/packimages.pl  -g $S/icon-themes/\breeze\galaxy\hicontrast\oxygen\sifr\tango -m $S/icon-themes/\breeze\galaxy\hicontrast\oxygen\sifr\tango -c $S/icon-themes/\breeze\galaxy\hicontrast\oxygen\sifr\tango    -l $W/CustomTarget/postprocess/images -l $W/ResTarget/ -l $W/UIConfig/ -l $W/UIConfig/modules/   -s $W/CustomTarget/postprocess/images/sorted.lst -o $W/CustomTarget/postprocess/images/images_\breeze\galaxy\hicontrast\oxygen\sifr\tango.zip > /dev/null
| [build PRL] CustomTarget/postprocess/images/images_export.zip
| packimages: ERROR: no such directory: '/mnt/sda1/projects/oe/oe-project/buildQ/tmp/work/core2-64-poky-linux/libreoffice/5.0.6.3-r0/libreoffice-5.0.6.3/icon-themes/breezegalaxyhicontrastoxygensifrtango'
| 
| FAILURE: packimages aborted.
| /mnt/sda1/projects/oe/oe-project/buildQ/tmp/work/core2-64-poky-linux/libreoffice/5.0.6.3-r0/libreoffice-5.0.6.3/postprocess/CustomTarget_images.mk:34: recipe for target '/mnt/sda1/projects/oe/oe-project/buildQ/tmp/work/core2-64-poky-linux/libreoffice/5.0.6.3-r0/libreoffice-5.0.6.3/workdir/CustomTarget/postprocess/images/images_\breeze\galaxy\hicontrast\oxygen\sifr\tango.zip' failed
| make[1]: *** [/mnt/sda1/projects/oe/oe-project/buildQ/tmp/work/core2-64-poky-linux/libreoffice/5.0.6.3-r0/libreoffice-5.0.6.3/workdir/CustomTarget/postprocess/images/images_\breeze\galaxy\hicontrast\oxygen\sifr\tango.zip] Error 2
| ERROR: oe_runmake failed
| make[1]: *** Waiting for unfinished jobs....
| make[1]: Leaving directory '/mnt/sda1/projects/oe/oe-project/buildQ/tmp/work/core2-64-poky-linux/libreoffice/5.0.6.3-r0/libreoffice-5.0.6.3'
| Makefile:247: recipe for target 'build' failed
| make: *** [build] Error 2
| ERROR: Function failed: do_compile (log file is located at /mnt/sda1/projects/oe/oe-project/buildQ/tmp/work/core2-64-poky-linux/libreoffice/5.0.6.3-r0/temp/log.do_compile.12815)
ERROR: Task (/mnt/sda1/projects/oe/oe-project/meta-office/recipes-libreoffice/libreoffice/libreoffice.bb:do_compile) failed with exit code '1'
```

Somehow, it has run the icon directories together:

tmp/work/core2-64-poky-linux/libreoffice/5.0.6.3-r0/libreoffice-5.0.6.3/icon-themes/breezegalaxyhicontrastoxygensifrtango

...they are actually separate directories, 'breeze', 'galaxy', etc.

Just to complete the build, I created an empty directory with that name 'breezegalaxyhicontrastoxygensifrtango', but got another error, it wanted another directory named 'export' alonside 'breezegalaxyhicontrastoxygensifrtango' so created that also.
Then compile completed.

This must be an error that others will encounter also? Perhaps no one has actually tried this libreoffice build for awhile?

There is nothing fancy about my setup. Building for MACHINE 'genericx86-64', target 'core-image-sato-sdk', with libreoffice added into bblayers.conf and local.conf. Cloned everything about a week ago, with "--depth 1", did not checkout a release version.
local.conf is almost the automatically created default, I just appended:

```
DISTRO_FEATURES_append = " opengl"
IMAGE_INSTALL_append = " streamripper pinpoint dhcpcd pure-ftpd pptp-linux rp-pppoe mtr hiawatha openbox gedit evince abiword gparted epiphany gphoto2 gimp firefox libreoffice"

```
...yep, all those others built. Only failure is libreoffice.

Note, if anyone else wants to reproduce my build exactly, I have posted steps on my blog:
http://barryk.org/news/?viewDetailed=00529
http://barryk.org/news/?viewDetailed=00530

...however, I have now added the meta-poky, meta-yocto and meta-yocto-bsp, so as to be able to build MACHINE = "genericx86-64" (in local.conf). I will post those changes to my blog.

**Comment by schnitzeltony** [comment]
As far as I remember I took your patches and now libreoffice recipe was upgraded to 6.2.6.1

If the problem persists, feel free to re-open
