### ISSUE TITLE
Yocto (sumo) reports QA issues with the libreoffice package

### ISSUE THREAD

**Issue by clopez** [schnitzeltony/meta-office#7]
When building libreoffice from meta-office with Yocto sumo the following QA issues is reported:

```
ERROR: libreoffice-5.0.6.3-r0 do_package: QA Issue: File '/usr/lib/libreoffice/share/extensions/mysql-connector-ooo/libmysqlclient_r.so' from libreoffice was already stripped, this will prevent future debugging! [already-stripped]
```

So I disabled mysql in the `PACKAGECONFIG` options, which i don't needed anyway.. but then I got this other QA issue:

```
ERROR: libreoffice-5.0.6.3-r0 do_package_qa: QA Issue: No GNU_HASH in the elf binary: [...]/libreoffice/5.0.6.3-r0/packages-split/libreoffice/usr/lib/libreoffice/program/liblpsolve55.so' [ldflags]
```

I workarounded it by adding `ldflags` to the `INSANE_SKIP` list

**Comment by schnitzeltony** [comment]
Fixed by fa7d3cf2246fa3f7fef89038ebf7bed1064dd9b9 / 7652f30ee9602b9b4c3cfa21347ac14d2f84b8dc
