### ISSUE TITLE
clucene-core check fails

### ISSUE THREAD

**Issue by megastallman** [schnitzeltony/meta-office#8]
Hi @schnitzeltony !
I'm trying to build libreoffice and get the following failure: https://hastebin.com/usihoruled.rb
More exactly - for some reason the architecture prefix has sneaked to the evaluation.
```
CMake Error at src/shared/cmake/MacroEnsureVersion.cmake:27 (MATH):
|   MATH cannot parse the expression: "x86_648*10000 + x86_641*100 + x86_640":
|   syntax error, unexpected exp_NUMBER, expecting $end (8)
| Call Stack (most recent call first):
|   src/shared/cmake/MacroCheckGccVisibility.cmake:35 (macro_ensure_version)
|   src/core/CMakeLists.txt:10 (MACRO_CHECK_GCC_VISIBILITY)
```

Thanks in advance!

**Comment by schnitzeltony** [comment]
Was not able to reproduce / pastebin link is gone.
If the problem persists, feel free to re-open
